# Permission Settings
Permissions:
  Require-Permission: false
  Permission: fredhunt.use
# Compass on Join
Join:
  Join-Compass: false # Give players a compass on join?
  Join-Player: "" # UUID of player to track on join. Set to "" to disable
# Message Settings
Messages:
  Send-Tracker-Track-Message: true
  Send-Player-Tracked-Message: false
# Gui Settings
Gui:
  Cooldown: false
  Cooldown-time: 3000 # Time in milliseconds, seconds * 1000
# Language
Language:
  Item-Name: "§aTracker Compass"
  Gui:
    Title: "Player Tracker"
    Click-To-Track: "§eClick To Track"
    Next: "§aNext"
    Back: "§cBack"
  Now-Tracking: "§a§lSuccess! §eNow Tracking [player]" # Available Variables: [player]
  Being-Tracked: "§e[player] &ais now tracking you" # Available Variables: [player]
  Missing-Permission: "§cError! §7You Can't Do That"
  Cooldown-Message: "§c§lError! §7Please Wait [seconds] Seconds" # Available Variables: [seconds]
  Errors:
    Offline-Player: "§c§lError! §7This Compass Is Tracking an Offline Player."
    Different-World: "§c§lError! §7This Player Is In A Different World"
    Invalid-UUID: "§c§lError! §7This Compass Contains an Invalid UUID. Please Report This Error"