name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && ls target | grep -v '^original' | grep '.*jar' | xargs cp "target/"-t staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
